server:
  port: 8001
dubbo:
  application:
    name: member
  protocol:
    name: dubbo
    port: 20881
  registry:
    address: zookeeper://192.168.72.128:2181
  scan:
    base-packages: com.huihuang.service.impl